### ISSUE TITLE
"##" not rendered properly in term mode

### ISSUE THREAD

**Issue by nkh** [kristapsdz/lowdown#100]
"# something" translates to  red+"something" while "## somethineg else" translates to green+"## something else", IE: the '#' stay.

this can be seen in your own example:
https://kristaps.bsd.lv/lowdown/screen-term.png

**Comment by nkh** [comment]
same goes for "###"

**Comment by kristapsdz** [comment]
This was from a patch from the Nix folks, and is set in *term.h*.  You can override this at compile-time by setting `pfx_header_n` for the prefixed '#' in n>1 headers, `pfx_header_1` for n=1 headers, and the colours in `sty_header_1` and `sty_header_n`, respectively.  Since there's no standard for this, it's just bike-shedding one way or another, so I'm probably not going to merge changes unless there's a glaringly good reason, and I think the existing way is good enough.
