### ISSUE TITLE
Non-portable font C

### ISSUE THREAD

**Issue by paravoid** [kristapsdz/lowdown#123]
This snippet:
```markdown
# OPTIONS

`--help`

:   Show the help message.
```

With newer versions of groff, as they exist now in Debian unstable, emits these warnings:
```
$ groff --version
GNU groff version 1.23.0
Copyright (C) 2022 Free Software Foundation, Inc.
GNU groff comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of groff and its subprograms
under the terms of the GNU General Public License.
For more information about these matters, see the file
named COPYING.

called subprograms:

GNU troff (groff) version 1.23.0
GNU grops (groff) version 1.23.0

$ lowdown -s -Tman -M title:TEST -M section:1 -Mdate:$(date -I -u) test.md | groff -Tascii -man >/dev/null 
troff:<standard input>:6: warning: cannot select font 'C'
```

Note that mandoc is also unhappy:
```
$ lowdown -s -Tman -M title:TEST -M section:1 -Mdate:$(date -I -u) test.md | mandoc -T lint
mandoc: <stdin>:6:1: WARNING: invalid escape sequence: \fC
mandoc: <stdin>:5:2: WARNING: skipping paragraph macro: PP after SH
```

[Debian bug #1041809](https://bugs.debian.org/1041809) against rst2man, exhibiting similar behavior, provides some additional context.

**Comment by paravoid** [comment]
[Debian bug #1043256](https://bugs.debian.org/1043256) has even more context.

**Comment by kristapsdz** [comment]
Hi faidon.  This is a tricky one... can you keep an eye on these commits and see if they work for you?

pandoc uses an `.ie` clause in the header and uses a custom `V` font, which doesn't play well with mandoc.  My solution is to use `B` (bold font) for **-tman** and `C` (constant-width) for **-tms** by default.  The user can override this with **--nroff-code-font**, which I've not yet finalised upon or documented.  (Later commits wihle I ruminate.)

This, I think, sets some useful defaults while letting the user override the output, playing reasonably well with groff and mandoc.

**Comment by g-branden-robinson** [comment]
Thomas Dickey [recently merged changes from me to his _ncurses_ man pages](https://github.com/ThomasDickey/ncurses-snapshots/commit/af0af804518d07b2f7efdbb6252263f42a93a359) that look like this.

```
.ie n .ds CW R
.el   \{
.ie \n(.g .ds CW CR
.el       .ds CW CW
.\}
```

This defines a _roff_ string named "CW".  Translated to English, this means...

- If formatting for a terminal (that is, "in _nroff_ mode"), define the string as "R" (the roman style--always available).
- Otherwise, we are formatting for a typesetter.
  - If the formatter claims _groff_ compatibility, use the font name "CR" ("Courier roman").
  - Otherwise, use the font name "CW" ("constant-width", from Unix System III _troff_ and later).

This _should_ cover all the bases.

* Any version of _groff_ will do the right thing.
* _mandoc_ will do the right thing because it always claims to be in _nroff_ mode, and it understands the `ds`, `ie`, and `el` requests well enough to cope.
* AT&T _troff_, nowadays seen only in Documenter's Workbench 3.3 _troff_ (which I think only _roff_ developers like me ever use) and proprietary Unices like Solaris and HP-UX, and sometimes not even those (due to adoption of _groff_, as in Solaris 11) will do the right thing because that _troff_ doesn't define the `.g` register, (by convention) claiming _groff_ compatibility.
* Heirloom Doctools _troff_ will emulate either _groff_ or AT&T Unix, as configured by the user.

The only aspect of this solution that I (and, I would guess, _mandoc_ maintainer @ischwarze) don't like is the resort to conditional requests and string definitions, because _as a general rule_, employment of formatter requests in man pages makes them less portable.  But there's really no way around this if one wants portability for _this_ specific problem--the [referenced _pandoc_ issue](https://github.com/jgm/pandoc/issues/9020) explains why--without giving up the use of monospaced fonts when typesetting _man_(7) pages altogether, which people are generally not willing to do.

_groff_ _man_(7)'s macros `EX` and `EE` are an alternative--if one is willing to embrace a Ninth Edition Unix (1986) extension--but are not fully suitable if one wants to use a monospaced font in a _tbl_(1) table.

**Comment by g-branden-robinson** [comment]
> pandoc uses an `.ie` clause in the header and uses a custom `V` font, which doesn't play well with mandoc.

[_pandoc_ doesn't do this anymore.](https://github.com/jgm/pandoc/commit/a6fe02f46a93c8cfaad1a4cb3c5e166a7aea3a4b)

**Comment by kristapsdz** [comment]
If pandoc's going to make a stand on using `CR`, I'll do the same as a default.  However, I'll keep the option available for people to override (e.g., with bold for terminals).

**Comment by kristapsdz** [comment]
If the new support looks good to you, please close out this issue.  Thanks!

**Comment by paravoid** [comment]
LGTM! @g-branden-robinson may have more thoughts as the expert, but I'll stay optimistic and close the issue.
