### ISSUE TITLE
New feature (with code): "pretty" paragraphs for -Tms

### ISSUE THREAD

**Issue by larrykollar** [kristapsdz/lowdown#31]
I've implemented a new option, `—nroff-pretty-para`, to use `.PP` except after headings, lists, tables, and code blocks (all of which are followed by `.LP`). Patch attached.

[lowdown_pretty_para.patch.txt](https://github.com/kristapsdz/lowdown/files/5026028/lowdown_pretty_para.patch.txt)

**Comment by kristapsdz** [comment]
Is this conventional in roff documents?  To me, the output looks much more confusing!

**Comment by larrykollar** [comment]
It's a typographical convention. I think LaTeX does it automatically, and the -mm macros can as well (set \n[Pt] to 2). You'll also see something similar in works of fiction, although there is usually only one (maybe two for long books) heading levels.

**Comment by kristapsdz** [comment]
If LaTeX does this automatically, then let's make -Tlatex and -Tms have the same output and use this as the default.  Right now I have **-Tlatex** disable the indentation with `\usepackage[parfill]{parskip}` because I don't like it, but I'd rather have the PDF output consistent between the two, and LaTeX is the more common.

What do you think about having the "pretty" paragraphs be the default for **-Tms**, using the default LaTeX for **-Tlatex**, and an option like `--latex-no-indent` and `--nroff-no-indent` to have indent-less output?

**Comment by larrykollar** [comment]
Works for me!

**Comment by kristapsdz** [comment]
Committed but in a significantly different patch.  Thanks again!  (I'll maybe add the block-paragraph bits in later.)  I'll roll this out in a release soon unless the patch is broken for your needs.
