### ISSUE TITLE
Can this library support installing a shared object?

### ISSUE THREAD

**Issue by Ericson2314** [kristapsdz/lowdown#45]
I have a patch for the Makefile at https://github.com/NixOS/nixpkgs/blob/be7f1c9cf06a231a06cd51775c900e5e579ff95e/pkgs/tools/typesetting/lowdown/shared.patch, but I don't know what to do about the autogenerated configure script.

**Comment by kristapsdz** [comment]
Hi John, I don't know much about packaging issues.  Is there an issue with lowdown here?  The `configure` script shouldn't play a part here.

**Comment by Ericson2314** [comment]
Well ideomatically, the choice of static or shared would be done by the configure script (See `--{enable,disable}-shared` with Autoconf, `-Ddefault_library={shared,static,both}` for Meson). But yes we could just change the Makefile with conditional code, allowing one to do e.g. `Make SHARED:=''` vs `Make SHARED:=1` or something.

**Comment by Ericson2314** [comment]
Tangential, but I should ask, do you care about how the current configure script works, or was that inherited from one of the things this was forked from? Because I also noticed it makes portability harder, since it includes checks that are not relevant for this program in particular. (e.g. some OS and crypto primitives). This made lowdown hard to get building in MinGW, when as it's mostly IO-free C code, it shouldn't be hard in principle.

**Comment by kristapsdz** [comment]
The configure script is from [oconfigure](https://github.com/kristapsdz/oconfigfure), whose tldr is that it provides me with an OpenBSD environment on non-OpenBSD *UNIX* system.  I don't work with non-UNIX at all, so that's just not on my radar.  But I'm happy to work with somebody willing to look into oconfigure so that it doesn't puke on non-UNIX environments.  This (I just passed ming as CC and CFLAGS to a ./configure), would entail not emitting some UNIX-specific prototypes at all, and the rest in providing basic types.

I'm going to mark this as "closed" for now, as it doesn't look like something to fix within lowdown: for shared libraries, patching the Makefile should do the trick.  As for mingw... I'm happy to look at patches, but it's not work I'll undertake myself.

**Comment by paravoid** [comment]
I think the oconfigure question may be tangential here :)

I think there is another question (that I was also -entirely separately!- wondering about myself) on whether liblowdown is intended to be used only with static linking, or also dynamically linked, with a liblowdown.so shipped a shared object with a stable ABI, SONAME, etc. Right now the build system just builds liblowdown.a, but not a .so. 

I'm not aware of any other users of liblowdown besides lowdown itself, so my guess was that you were not shipping a .so as to not make any ABI guarantees yet; and that if other users popped up in the future, you'd probably consider a .so with a stable ABI. Is that a fair guess?

**Comment by kristapsdz** [comment]
I use liblowdown for my own needs and am not aware of any other consumers.  My own needs call for static archives---I've no opinions on the matter.

Thing is, liblowdown isn't great for library purposes (yet) because the backend functions will exit(3) on memory allocation errors instead of returning `NULL` or similar.  This isn't hard to change but one of those dreadfully boring and mechanical efforts of going through every file and changing every alloc-reaching function to have a return value.  Same with the parser (document.c) using err(3) and friends instead of queueing messages.

I'm happy to provide a .so as well, but these trivial-but-boring issues need to be addressed to make the library a proper one.

**Comment by sternenseemann** [comment]
Experimental versions of the Nix package manager [use lowdown](https://github.com/NixOS/nix/blob/57b935a8931fb59cdfe521357e76326d467a9a86/src/nix/markdown.cc).

**Comment by kristapsdz** [comment]
Cool.  I use **-Tterm** quite a lot, so it gets usage.  You shouldn't need the "extern C" bits in that code, as *lowdown.h* already does that.  (I guess---I rarely use C++.)  Be aware of the internal exit(3) on memory allocation failure and possible printing to stderr, however!
