### ISSUE TITLE
URL handling in -Tman

### ISSUE THREAD

**Issue by paravoid** [kristapsdz/lowdown#53]
Imagine this excerpt:
```markdown
Please report all issues to
[our GitHub issue tracker](https://github.com/kristapsdz/lowdown/issues).
```

The `-Thtml` output is, somewhat obviously :)
```html
<p>Please report all issues to
<a href="https://github.com/kristapsdz/lowdown/issues">our GitHub issue tracker</a>.</p>
```

But, the `-Tman` output is:
```roff
.PP
Please report all issues to
\f[I]our GitHub issue tracker\f[R].
```

In other words, the URL is lost from the HTML output. A user that is looking at that man page does not know where they should report that bug report, or what link to click.

pandoc adds the URL in parenthesis after the text (```our GitHub issue
tracker (https://github.com/kristapsdz/lowdown/issues)```, for what it's worth :)

**Comment by kristapsdz** [comment]
This has been fixed with the last checkins, which format links (e.g., `[foo](bar)`) as **foo** (*bar*), autolinks (e.g., `www.foo.com`) as *www .foo.com*, and images as (e.g., `![foo](bar)`) as **foo** (Image: *bar*).  This happens with **-Tman** or either troff formatter when invoked with **--nroff-no-groff**.

This behaviour may be modified by **--nroff-shortlinks** and **--nroff-nolinks**.  The former will shorten all URLs as also done in **-Tterm**.  The latter will inhibit URLs for links and images, showing only the textual content.  Both used together will inhibit URLs for links and images, and shorten those for autolinks.

This will be part of 0.8.1, thank you!
