### ISSUE TITLE
how can i uninstall or remove lowdown?

### ISSUE THREAD

**Issue by 45230** [kristapsdz/lowdown#67]
how can i uninstall or remove lowdown?

**Comment by kristapsdz** [comment]
How did you install it?

**Comment by 45230** [comment]
downloaded and used `sudo make install` to install Lowdown



At 2021-05-26 20:58:31, "Kristaps Dz" ***@***.***> wrote:

How did you install it?

**Comment by kristapsdz** [comment]
If lowdown isn't packaged with your operating system, you may want to prod the team to package it for you---or do so yourself.  I don't support an `uninstall` hook for `make` because I don't use the software like this, but you can always run:

```
% ./configure PREFIX=build
% make install
% find ./build
``

This will install into the *build* directory, then list all that's installed.  You can then find these files wherever you installed them and remove them manually.  For example, for me it's:

```
% find build/                                                                                                                                                                                                                                                                              
build/
build/bin
build/bin/lowdown
build/bin/lowdown-diff
build/lib
build/lib/pkgconfig
build/lib/pkgconfig/lowdown.pc
build/lib/liblowdown.a
build/include
build/include/lowdown.h
build/man
build/man/man1
build/man/man1/lowdown.1
build/man/man1/lowdown-diff.1
build/man/man3
build/man/man3/lowdown.3
build/man/man3/lowdown_buf.3
build/man/man3/lowdown_buf_diff.3
build/man/man3/lowdown_buf_free.3
build/man/man3/lowdown_buf_new.3
build/man/man3/lowdown_diff.3
build/man/man3/lowdown_doc_free.3
build/man/man3/lowdown_doc_new.3
build/man/man3/lowdown_doc_parse.3
build/man/man3/lowdown_file.3
build/man/man3/lowdown_file_diff.3
build/man/man3/lowdown_gemini_free.3
build/man/man3/lowdown_gemini_new.3
build/man/man3/lowdown_gemini_rndr.3
build/man/man3/lowdown_html_free.3
build/man/man3/lowdown_html_new.3
build/man/man3/lowdown_html_rndr.3
build/man/man3/lowdown_latex_free.3
build/man/man3/lowdown_latex_new.3
build/man/man3/lowdown_latex_rndr.3
build/man/man3/lowdown_metaq_free.3
build/man/man3/lowdown_node_free.3
build/man/man3/lowdown_nroff_free.3
build/man/man3/lowdown_nroff_new.3
build/man/man3/lowdown_nroff_rndr.3
build/man/man3/lowdown_term_free.3
build/man/man3/lowdown_term_new.3
build/man/man3/lowdown_term_rndr.3
build/man/man3/lowdown_tree_rndr.3
build/man/man5
build/man/man5/lowdown.5
```

**Comment by 45230** [comment]
thanks
