### ISSUE TITLE
exclamation point immediately before a footnote reference is removed

### ISSUE THREAD

**Issue by redschalken** [kristapsdz/lowdown#68]
Consider this simple file, `test.txt`:

```
This is a test![^01]

[^01]: footnote text.
```

Note the exclamation point before the footnote reference. Now when I run `lowdown test.txt` I get this, in which that exclamation point is missing:

```
<p>This is a test<sup id="fnref1"><a href="#fn1" rel="footnote">1</a></sup></p>

<div class="footnotes">
<hr/>
<ol>

<li id="fn1">
<p>Footnote&#160;<a href="#fnref1" rev="footnote">&#8617;</a></p>
</li>

</ol>
</div>
```
In all output modes, the exclamation point immediately before a footnote reference is removed.

I noticed this on lowdown 0.8.3 and 0.8.4. on OpenBSD -current.

**Comment by kristapsdz** [comment]
Great find!  It happens because the `!` triggers a link (image) parse, which then about-faces for being metadata instead of a link, and the `!` is lost.  Metadata (offset with `%` instead of `^` is also affected, as is simply `![^01] without `01` being a legitimate reference.)

However, this is a situation of ambiguous parsing: is it an image, or is it a footnote?  It makes sense to me that the special character what would be the "alt" text triggers the special handling.  Can you verify with other parsers that this happens?

If so, I'll submit the fix, add the regression tests, then also add documentation that images with "alt" text starting with `%` or `^` need to be escaped.

**Comment by kristapsdz** [comment]
**Update**: it turns out that `%` or `^` starting the alt text is impossible, as the alt text is interpreted as-is and not stripped for escape characters.  Markdown... I've modified the manpage to note this.
