### ISSUE TITLE
Latex footnotes are not placed where expected

### ISSUE THREAD

**Issue by orachux** [kristapsdz/lowdown#80]
Hi there.

given the following markdown `test.md`

```
title: test

Lowdown rocks![^1]
[^1]: https://kristaps.bsd.lv/lowdown

This is a new paragraph.

This is a new paragraph.
```

`$ lowdown -sTlatex test.md`

gives 

```
\documentclass[11pt,a4paper]{article}
\usepackage{xcolor}
\usepackage{graphicx}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{textcomp}
\usepackage{lmodern}
\usepackage{hyperref}
\usepackage{amsmath}
\usepackage{amssymb}
\begin{document}
\title{test}
\maketitle

Lowdown rocks!\footnotemark[1]
This is a new paragraph.

This is a new paragraph.
\footnotetext[1]{
\url{https://kristaps.bsd.lv/lowdown}
}
\end{document}
```

Expected something like:
```
\documentclass[11pt,a4paper]{article}
\usepackage{xcolor}
\usepackage{graphicx}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{textcomp}
\usepackage{lmodern}
\usepackage{hyperref}
\usepackage{amsmath}
\usepackage{amssymb}
\begin{document}
\title{test}
\maketitle

Lowdown rocks!\footnotemark[1]
\footnotetext[1]{
\url{https://kristaps.bsd.lv/lowdown}
}

This is a new paragraph.

This is a new paragraph.
\end{document}
```

Why is this a problem?

For instance, when converting  a longer latex document with many footnotes to pdf, the footnotes will end up at the end of a document, and not on the page where they actually occur.

PS: I am not a latex guru, but after some time of investigating the _\footnotemark_ and _\footnotetext_ commands as well as the [_footmisc_ package](https://www.ctan.org/pkg/footmisc) I believe my expectation is correct. Please correct me if not.

**Comment by kristapsdz** [comment]
It's not clear in Markdown whether the footnotes are supposed to be footnotes or, well, endnotes.  Since Markdown doesn't specify which, I just guessed.  It's certainly possible to put these into the text stream---odt.c does this by collecting all references beforehand.

What I'd like to see is both the roff (**-man** and **-ms**) and latex output have switches for rendering footnotes or endnotes. Do you feel up to tackling this?  The latex one is fairly straightforward, but the roff one needs a little elbow grease in figuring out the best macros to use for the job.  (This is even noted on the website's TODO part.)

**Comment by tweedyf** [comment]
Chiming in to say that for -Tms this is an actual problem rather than just a stylistic choice. In that format, they are rendered as footnotes to the final page, not as endnotes, with the result that if you have more notes than can fit as footnotes to the final page, many simply don't appear at all.

I'd be happy to look into the switch solution you proposed to orachux, but I may lack the expertise to pull it off.

**Comment by kristapsdz** [comment]
This is currently in the repository, if you'd like to check it out!  I specifically mean **-Tfodt** and **-Tms** using footnotes and not endnotes.

**Comment by tweedyf** [comment]
Amazing! Looks good on a test -Tms document I just ran.

**Comment by kristapsdz** [comment]
Closing this as it'll appear in the next release, thanks!
